export default defineNuxtConfig({
  modules: ['@nuxt/ui', '@openape/nuxt-auth-idp', '@openape/nuxt-grants'],
  css: ['~/assets/css/main.css'],
  devtools: { enabled: true },
  devServer: { port: 3000 },
  compatibilityDate: '2025-01-01',
  colorMode: {
    preference: 'dark',
  },
  openapeIdp: {
    storageDriver: process.env.NUXT_OPENAPE_STORAGE_DRIVER || '',
    storagePath: process.env.NUXT_OPENAPE_STORAGE_PATH || './.data/openape-idp-db',
    adminEmails: process.env.NUXT_OPENAPE_ADMIN_EMAILS || '',
    managementToken: process.env.NUXT_OPENAPE_MANAGEMENT_TOKEN || '',
    sessionSecret: process.env.NUXT_OPENAPE_SESSION_SECRET || 'change-me-to-a-real-secret-at-least-32-chars',
    issuer: process.env.NUXT_OPENAPE_ISSUER || '',
    rpName: process.env.NUXT_OPENAPE_RP_NAME || 'OpenApe Identity',
    rpID: process.env.NUXT_OPENAPE_RP_ID || 'localhost',
    rpOrigin: process.env.NUXT_OPENAPE_RP_ORIGIN || 'http://localhost:3000',
    requireUserVerification: process.env.NUXT_OPENAPE_REQUIRE_USER_VERIFICATION === 'true',
    residentKey: (process.env.NUXT_OPENAPE_RESIDENT_KEY as 'preferred' | 'required' | 'discouraged') || 'preferred',
    attestationType: (process.env.NUXT_OPENAPE_ATTESTATION_TYPE as 'none' | 'indirect' | 'direct' | 'enterprise') || 'none',
    s3: {
      accessKeyId: process.env.NUXT_OPENAPE_S3_ACCESS_KEY || '',
      secretAccessKey: process.env.NUXT_OPENAPE_S3_SECRET_KEY || '',
      bucket: process.env.NUXT_OPENAPE_S3_BUCKET || 'dnsid',
      endpoint: process.env.NUXT_OPENAPE_S3_ENDPOINT || 'https://sos-at-vie-2.exo.io',
      region: process.env.NUXT_OPENAPE_S3_REGION || 'at-vie-2',
      prefix: process.env.NUXT_OPENAPE_S3_PREFIX || 'openape-idp/',
    },
  },
  openapeGrants: {
    enablePages: true,
  },
})
